name: MyCI
on: [push]
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'yarn'
      - name: Install project dependencies
        run: yarn install
  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: build
        run: yarn build
  linters:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: linters
        run: yarn linters
  deploy:
    runs-on: ubuntu-latest
    needs: [dependencies, build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: deploy
        run: yarn deploy
    
      
