name: MyCI
on: [push]
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x' # Укажите версию Node.js
          check-latest: true
          cache: 'yarn'                
      - name: Install project dependencies
        run: yarn install --immutable
  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x' # Укажите версию Node.js
          check-latest: true
          cache: 'yarn'                
      - name: Install project dependencies
        run: yarn install --immutable
      - name: build
        run: yarn build
  linters:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x' # Укажите версию Node.js
          check-latest: true
          cache: 'yarn'                
      - name: Install project dependencies
        run: yarn install --immutable
      - name: linters
        run: yarn linters
  deploy:
    runs-on: ubuntu-latest
    needs: [dependencies, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x' # Укажите версию Node.js
          check-latest: true
          cache: 'yarn'                
      - name: Install project dependencies
        run: yarn install --immutable
      - name: deploy
        run: yarn deploy
    
      
