name: MyCI
on: [push]
jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          check-latest: true
          cache: 'yarn'
      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}  
      - name: Debug cache content
        run: ls -la ~/.yarn/berry/cache
      - name: Install project dependencies
        run: yarn install 
  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          check-latest: true
      - name: Use cached dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}          
      - name: Debug cache content
        run: ls -la ~/.yarn/berry/cache
      - name: Install project dependencies
        run: yarn install 
      - name: build
        run: yarn build
  linters:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          check-latest: true
      - name: Use cached dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}         
      - name: Install project dependencies
        run: yarn install 
      - name: linters
        run: yarn linters
  deploy:
    runs-on: ubuntu-latest
    needs: [dependencies, build]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.x'
          check-latest: true
      - name: Use cached dependencies
        uses: actions/cache@v4
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}           
      - name: Install project dependencies
        run: yarn install 
      - name: deploy
        run: yarn deploy
    
      
